#!/bin/bash
set -e

echo "### installing basic apps ###"

sudo pacman -S --noconfirm --needed vivaldi vivaldi-ffmpeg-codecs termite tmux pcmanfm-gtk3 htop scrot imagemagick thunar gvfs thunar-volman ranger w3m sublime-text/sublime-text vim

trizen -S --noedit --noconfirm vivaldi-widevine

trizen -S --noedit --noconfirm  arch-wiki-man gotop-bin

echo "### basic apps installed ###"

echo "### installing openbox related apps ###"

sudo pacman -S --noconfirm --needed obconf lxappearance-gtk3 neofetch oblogout zenity dunst feh nitrogen rofi dmenu xfce4-appfinder gmrun numlockx compton python-pywal

#sudo pacman -S --noconfirm --needed lxappearance-obconf-gtk3

trizen -S --noconfirm --noedit obmenu3 obmenu-generator obkey

echo "### openbox related apps installed ###"

echo "### installing zippers and unzippers ###"

sudo pacman -S --noconfirm --needed unace unrar zip unzip sharutils uudeview arj cabextract file-roller p7zip

echo "### zippers and unzippers installed ###"

echo "### installing polybar ###"

# tools needed for polybar

sudo pacman -S --noconfirm --needed wireless_tools jq libmpdclient

# trizen -S --noconfirm --noedit ttf-weather-icons

trizen -S --noconfirm --noedit polybar-git

echo "### polybar installed ###"

echo "### installing zsh ###"

sudo pacman -S --noconfirm --needed zsh zsh-completions zsh-syntax-highlighting thefuck

echo "### zsh installed ###"

echo "### installing oh-my-zsh ###"

sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

echo "### oh-my-zsh installed ###"

echo "### installing oh-my-zsh plugins ###"

cd ~/.oh-my-zsh/custom/plugins

git clone https://github.com/zsh-users/zsh-syntax-highlighting

git clone https://github.com/zsh-users/zsh-autosuggestions

echo "### oh-my-zsh plugins installed ###"

echo "If you now log out and log in again, you will be greeted by the other shell (chsh -s /bin/zsh)"
