#!/bin/sh
# https://gist.github.com/febuiles/1549991

set -e

mpc_query() {
	mpc -f "$1" current
}

artist=$(mpc_query %artist%)
title=$(mpc_query %title%)
album=$(mpc_query %album%)

lyrics=$(beet lyrics -p $artist $title $album 2>/dev/null)

printf "%s - %s (%s)\n\n%s\n" "$artist" "$title" "$album" "$lyrics"

read -n1 -r -p ''