#!/bin/bash
set -e

# update pacman packages
sudo pacman -Syu --noconfirm 

echo "### pacman packages updated ###"

# clean pacman cache
sudo pacman -Sc --noconfirm --clean --clean

#echo "### pacman cache cleaned ###"
sudo paccache -rk 2

# update aur packages
trizen -Syua --noconfirm --noedit

echo "### aur packages updated ###"

# refresh polybar
polybar-msg cmd restart

read -n1 -r -p ''
